<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
		<IsPackable>false</IsPackable>
		<ImplicitUsings>true</ImplicitUsings>
		<RunSettingsFilePath>D:\Users\essence\Development\- GitHub\- Open-NET-Libraries\Open.Database.Extensions\Tests\Open.Database.Extensions.Core.Tests\bin\Release\net9.0\fine-code-coverage\coverage-tool-output\Open.Database.Extensions.Core.Tests-fcc-mscodecoverage-generated.runsettings</RunSettingsFilePath>
	</PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.8.1" />
    <PackageReference Include="NSubstitute" Version="6.2.0" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="coverlet.collector" Version="10.0.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Source\Channel\Open.Database.Extensions.Channel.csproj" />
    <ProjectReference Include="..\..\Source\Core\Open.Database.Extensions.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="IDbCommand\" />
  </ItemGroup>

</Project>
